---
name: exercise10

on:
    pull_request:
        branches:
            - dev
            - main

jobs:
    exercise9:
        runs-on: ubuntu-latest
        steps:
            - name: learing
              run: "echo thanks for pull request"


